/**
 * Routes configuration for the {@link OnBoardingNavigator.tsx}
 */
const ONBOARDING_ROUTES = {
  // Onboarding section
  MAIN: 'ONBOARDING_MAIN',
  CAROUSEL: 'ONBOARDING_CAROUSEL',
  START: 'ONBOARDING_START',
  PIN: {
    CREATION: 'ONBOARDING_PIN_CREATION'
  },
  BIOMETRIC: {
    AVAILABLE: 'ONBOARDING_BIOMETRIC_AVAILABLE',
    NOT_ENROLLED: 'ONBOARDING_BIOMETRIC_NOT_ENROLLED',
    NO_SCREEN_LOCK: 'ONBOARDING_BIOMETRIC_NO_SCREEN_LOCK'
  }
} as const;

export default ONBOARDING_ROUTES;
