# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Submit a new beta build to TestFlight"
  lane :beta_testflight do |options|
    # Setup the CI environment
    setup_ci()

    # use the App Store API Key to authenticate
    api_key = app_store_connect_api_key(
      key_id: "#{ENV['APP_STORE_API_KEY_ID']}",
      issuer_id: "#{ENV['APP_STORE_API_KEY_ISSUER_ID']}",
      key_filepath: "./fastlane/AuthKey_#{ENV['APP_STORE_API_KEY_ID']}.p8",
      duration: 1200,
    )

    sync_code_signing(type: "appstore", api_key: api_key)

    # Install pods
    cocoapods

    # Increment the version number based on the bump_type parameter
    increment_version_number(version_number: options[:version])

    # increment the build number 
    increment_build_number

    # build the app
    gym(
      scheme: "AgeVerification",
      clean: true,
      export_method: "app-store",
      workspace: "AgeVerification.xcworkspace",
      include_symbols: false
    )

    previous_tag = sh("git tag --sort=-taggerdate | grep \\\\-rc\\\\. | sed -n '2 p' | tr -d '\n'")

    # generate the changelog based on last commits
    changelog = changelog_from_git_commits(
      tag_match_pattern: "*" +previous_tag + "*" ,
      pretty:"- %s",
      merge_commit_filtering: "exclude_merges"
    )

    # upload to App store
    pilot(
      api_key: api_key,
      changelog: changelog,
      # max wait for App Store Connect processing (30 min)
      wait_processing_timeout_duration: 1800
    )
  end
end
