name: "Pull request title linting"

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  pr-title-conventional-commit-validation:
    name: "Conventional commit validation"
    runs-on: ubuntu-22.04
    env:
      VALID_TYPES: "feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert"
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      COMMENT_TITLE: "## PR Title Validation for conventional commit type"
      # https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
      TITLE: ${{ github.event.pull_request.title }}
    steps:
      - name: Check if title follows conventional commit format
        run: |
          PR_TITLE="$TITLE"
          if [[ "$PR_TITLE" =~ ^([a-z]+)(\(([ a-zA-Z0-9_-]+)\))?:[[:space:]]*(.+)$ ]]; then
            TYPE=${BASH_REMATCH[1]}
            CONTEXT=${BASH_REMATCH[3]}
            DESCRIPTION=${BASH_REMATCH[4]}
            echo fix: $TYPE
            echo context: $CONTEXT
            echo description: $DESCRIPTION
            echo "PR_TYPE=$TYPE" >> $GITHUB_ENV
            echo "PR_CONTEXT=$CONTEXT" >> $GITHUB_ENV
            echo "PR_DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV
            if [[ ! "$TYPE" =~ ^($VALID_TYPES)$ ]]; then
              echo "VALIDATION_RESULT=warning" >> $GITHUB_ENV
            else
              echo "VALIDATION_RESULT=success" >> $GITHUB_ENV
            fi
          else
            echo "VALIDATION_RESULT=failure" >> $GITHUB_ENV
          fi

      - name: Find Existing Comment
        run: |
          EXISTING_COMMENT=$(gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            --jq ".[] | select(.body | startswith(\"$COMMENT_TITLE\")) | .id")          
          COMMENT_COUNT=$(echo "$EXISTING_COMMENT" | wc -l)
          if [ "$COMMENT_COUNT" -gt 1 ]; then
            echo "Multiple comments found with the same title. Please review the comments."
            exit 2
          else
            echo "EXISTING_COMMENT_ID=$EXISTING_COMMENT" >> $GITHUB_ENV
          fi

      - name: Add or Update Comment
        run: |
          COMMENT_BODY="$COMMENT_TITLE"$'\n\n'
          if [[ "${{ env.VALIDATION_RESULT }}" == "success" ]]; then
            COMMENT_BODY+=":white_check_mark: **All good!** PR title follows the conventional commit type."
          elif [[ "${{ env.VALIDATION_RESULT }}" == "warning" ]]; then
            COMMENT_BODY+=":warning: **PR title is valid**, but uses an unconventional type."
          else
            COMMENT_BODY+=":x: **PR title is invalid.**"$'\n'
            COMMENT_BODY+="It must follow the format \`type(context): description\`."$'\n\n'
            COMMENT_BODY+="**Valid types:**"$'\n'
            COMMENT_BODY+="- \`feat\`"$'\n'
            COMMENT_BODY+="- \`fix\`"$'\n'
            COMMENT_BODY+="- \`docs\`"$'\n'
            COMMENT_BODY+="- \`style\`"$'\n'
            COMMENT_BODY+="- \`refactor\`"$'\n'
            COMMENT_BODY+="- \`perf\`"$'\n'
            COMMENT_BODY+="- \`test\`"$'\n'
            COMMENT_BODY+="- \`build\`"$'\n'
            COMMENT_BODY+="- \`ci\`"$'\n'
            COMMENT_BODY+="- \`chore\`"$'\n'
            COMMENT_BODY+="- \`revert\`"
          fi

          if [[ -n "${{ env.EXISTING_COMMENT_ID }}" ]]; then
            # Update the existing comment
            gh api repos/${{ github.repository }}/issues/comments/${{ env.EXISTING_COMMENT_ID }} \
              -X PATCH -F body="$COMMENT_BODY"
          else
            # Create a new comment
            gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
              -X POST -F body="$COMMENT_BODY"
          fi

      - name: Fail if Title Invalid
        if: ${{ env.VALIDATION_RESULT == 'failure' }}
        run: |
          echo "Pull request title ($TITLE) is not properly formatted."
          exit 1
  pr-title-jira-validation:
    name: "Jira issue validation"
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      COMMENT_TITLE: "## Jira Pull Request Link"
      # https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
      TITLE: ${{ github.event.pull_request.title }}
      PR_TITLE_SAFE: ${{ github.event.pull_request.title }}
    steps:
      - name: Check if title contains Jira issue keys
        run: |
          PR_TITLE="$TITLE"
          if [[ "$PR_TITLE" =~ \[(#?[A-Z]*-[0-9]*,?){1,}\] ]]; then
            echo "PR title is valid."
            echo "VALIDATION_RESULT=success" >> $GITHUB_ENV
          else
            echo "PR title is invalid."
            echo "VALIDATION_RESULT=failure" >> $GITHUB_ENV
          fi

      - name: Find existing Jira comment
        run: |
          EXISTING_COMMENT=$(gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            --jq ".[] | select(.body | startswith(\"$COMMENT_TITLE\")) | .id")          
          COMMENT_COUNT=$(echo "$EXISTING_COMMENT" | wc -l)
          if [ "$COMMENT_COUNT" -gt 1 ]; then
            echo "Multiple comments found with the same title. Please review the comments."
            exit 2
          else
            echo "EXISTING_COMMENT_ID=$EXISTING_COMMENT" >> $GITHUB_ENV
          fi

      - name: Create or update Jira link comment
        run: |
          if [[ "${{ env.VALIDATION_RESULT }}" == "success" ]]; then
            PR_TITLE="$TITLE"
            ISSUES_STR=$(awk -F'\\[|\\]' '{print $2}' <<< "$PR_TITLE" | sed "s/#//g")
            IFS=',' read -ra ISSUES <<< "$ISSUES_STR"
            JIRA_COMMENT_MARKDOWN="$COMMENT_TITLE"$'\n\n'
            JIRA_COMMENT_MARKDOWN+="This Pull Request refers to Jira issues:"$'\n'

            for ISSUE in "${ISSUES[@]}"; do
              ISSUE=$(echo "$ISSUE" | sed 's/^ *//;s/ *$//') # Trim spaces
              JIRA_COMMENT_MARKDOWN+="- [$ISSUE](https://pagopa.atlassian.net/browse/$ISSUE)"$'\n'
            done

            echo "Gira comment markdown: $JIRA_COMMENT_MARKDOWN"          
            COMMENT_BODY=$JIRA_COMMENT_MARKDOWN
          else 
            COMMENT_BODY="${{ env.COMMENT_TITLE }}"$'\n\n'
            COMMENT_BODY+=":x: The PR title is wrongly formatted."$'\n'
            COMMENT_BODY+="Example -> chore: [TICKET] your title"
          fi

          echo "Comment body: $COMMENT_BODY"

          if [[ -n "${{ env.EXISTING_COMMENT_ID }}" ]]; then
            echo Update existing comment
            gh api repos/${{ github.repository }}/issues/comments/${{ env.EXISTING_COMMENT_ID }} \
              -X PATCH -F body="$COMMENT_BODY"
          else
            gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
              -X POST -F body="$COMMENT_BODY"
          fi

      - name: Failure message
        if: env.VALIDATION_RESULT != 'success'
        run: |
          echo "Pull request title ($PR_TITLE_SAFE) is not properly formatted or it is not related to any Jira issue"
          exit 1